name: dfmt
version: 0.12.0
summary: Code formatter for the D programming language
description: |
  Command-line utility to apply fixed code-formatting style to programs
  written in the D programming language.
confinement: classic
grade: stable

apps:
  dfmt:
    command: bin/dfmt

parts:
  dfmt:
    source: https://github.com/dlang-community/dfmt.git
    source-tag: v0.12.0
    source-type: git
    plugin: make
    makefile: makefile
    make-parameters:
      - DMD=/snap/bin/dmd
    artifacts:
      - bin/dfmt
    build-snaps:
    - dmd
    build-packages:
    - build-essential
